### ISSUE TITLE
segfault on 2nd connect

### ISSUE THREAD

**Issue by dl9pf** [longshine/ser2nets#2]
Hi !

Thanks for ser2nets - exactly what I am looking for.

I get a segfault, when I try to connect to the same port twice:
# /usr/sbin/ser2nets -c /etc/ser2net.conf -n -d

[D] tcps: 3 (0, 0)
[D] tcps: 3 (0, 7) 7 (3, 0)
Segmentation fault (core dumped)
# gdb ser2net core

GNU gdb (GDB) 7.4.1-debian
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "arm-linux-gnueabihf".
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/...
Reading symbols from /root/ser2nets/ser2net...done.

warning: core file may not match specified executable file.
[New LWP 7950]
Core was generated by `/usr/sbin/ser2nets -c /etc/ser2net.conf -n -d'.
Program terminated with signal 11, Segmentation fault.
#0  0x00000004 in ?? ()

(gdb) bt
#0  0x00000004 in ?? ()
#1  0x0000f5ea in sel_select_once (sel=0x19b008) at selector.c:807
#2  0x0000f6f6 in sel_select_loop (sel=0x19b008) at selector.c:843
#3  0x00009806 in main (argc=<optimized out>, argv=<optimized out>) at ser2net.c:331

(gdb) 

Configuration:
7001:telnet:60:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT banner

**Comment by longshine** [comment]
Sorry for the break down :(
We are working on it.

**Comment by longshine** [comment]
We are still developing the v2.9 branch to make it work. It may take another few days.
Before that, please refer to the 2.7 branch, which works fine on multi-connections.
Src: https://github.com/longshine/ser2nets/tree/2.7

**Comment by longshine** [comment]
I found that the write handler was not set correctly for incoming tcps other the first one.

``` bash
fd: 4, r: 0x8050710, w: 0x8050440
fd: 6, r: 0x8050710, w: 0x3
```

I've made a commit to fix this issue. Please let me know if it works for you. Thanks.
